//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.smart_school.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Demo_smart_school_DbEntities : DbContext
    {
        public Demo_smart_school_DbEntities()
            : base("name=Demo_smart_school_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmissionEnquiry> tblAdmissionEnquiries { get; set; }
        public virtual DbSet<tbl_Menus> tbl_Menus { get; set; }
        public virtual DbSet<tbl_SubMenu> tbl_SubMenu { get; set; }
        public virtual DbSet<tbl_UserHasMenus> tbl_UserHasMenus { get; set; }
        public virtual DbSet<tblSuperuser> tblSuperusers { get; set; }
    }
}
