//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.smart_school.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubMenu
    {
        public int sid { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string submenu_name { get; set; }
    }
}
