//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.smart_school.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmissionEnquiry
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string descri { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> nextfdate { get; set; }
        public string assigned { get; set; }
        public string reference { get; set; }
        public string sourc { get; set; }
        public string classs { get; set; }
        public string noofchild { get; set; }
        public string status { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
