//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.smart_school.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuperuser
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string role { get; set; }
        public string ipname { get; set; }
        public string ipadd { get; set; }
        public string logindate { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
